-- bgmeter :: zenimax/constants.lua
-- The ZeniMax API boundary. Every raw engine enum bgmeter relies on is
-- re-exported here, namespaced, so the rest of the addon never reads a bare
-- global. If ZOS renames an enum, this is the single file that changes.

BGMeter = BGMeter or {}
local BGMeter = BGMeter

BGMeter.zenimax = BGMeter.zenimax or {}

local C = {}

-- ── Battleground match lifecycle ──────────────────────────────────────────
C.EVENT_ADD_ON_LOADED              = EVENT_ADD_ON_LOADED
C.EVENT_PLAYER_ACTIVATED          = EVENT_PLAYER_ACTIVATED
C.EVENT_PLAYER_COMBAT_STATE       = EVENT_PLAYER_COMBAT_STATE
C.EVENT_BATTLEGROUND_STATE_CHANGED = EVENT_BATTLEGROUND_STATE_CHANGED
C.EVENT_BATTLEGROUND_SCOREBOARD_UPDATED = EVENT_BATTLEGROUND_SCOREBOARD_UPDATED
C.EVENT_BATTLEGROUND_KILL          = EVENT_BATTLEGROUND_KILL

C.BATTLEGROUND_STATE_NONE      = BATTLEGROUND_STATE_NONE
C.BATTLEGROUND_STATE_PREROUND  = BATTLEGROUND_STATE_PREROUND
C.BATTLEGROUND_STATE_STARTING  = BATTLEGROUND_STATE_STARTING
C.BATTLEGROUND_STATE_RUNNING   = BATTLEGROUND_STATE_RUNNING
C.BATTLEGROUND_STATE_POSTROUND = BATTLEGROUND_STATE_POSTROUND
C.BATTLEGROUND_STATE_FINISHED  = BATTLEGROUND_STATE_FINISHED

-- ── Scoreboard per-player score types ─────────────────────────────────────
C.SCORE_TRACKER_TYPE_SCORE        = SCORE_TRACKER_TYPE_SCORE
C.SCORE_TRACKER_TYPE_KILL         = SCORE_TRACKER_TYPE_KILL
C.SCORE_TRACKER_TYPE_DEATH        = SCORE_TRACKER_TYPE_DEATH
C.SCORE_TRACKER_TYPE_ASSISTS      = SCORE_TRACKER_TYPE_ASSISTS
C.SCORE_TRACKER_TYPE_DAMAGE_DONE  = SCORE_TRACKER_TYPE_DAMAGE_DONE
C.SCORE_TRACKER_TYPE_HEALING_DONE = SCORE_TRACKER_TYPE_HEALING_DONE
C.SCORE_TRACKER_TYPE_DAMAGE_TAKEN = SCORE_TRACKER_TYPE_DAMAGE_TAKEN

-- ── Progression: AP / XP / Champion ───────────────────────────────────────
C.EVENT_ALLIANCE_POINT_UPDATE = EVENT_ALLIANCE_POINT_UPDATE
C.EVENT_EXPERIENCE_GAIN       = EVENT_EXPERIENCE_GAIN
C.EVENT_CHAMPION_POINT_GAINED = EVENT_CHAMPION_POINT_GAINED

C.CURT_ALLIANCE_POINTS        = CURT_ALLIANCE_POINTS
C.CURRENCY_LOCATION_CHARACTER = CURRENCY_LOCATION_CHARACTER

-- ── AP source attribution (CurrencyChangeReason) ──────────────────────────
-- EVENT_ALLIANCE_POINT_UPDATE now passes a `reason` (CurrencyChangeReason) as
-- its 4th arg, so AP gains in Cyrodiil/IC can be split by what earned them.
-- These enums are nil-safe: an absent one simply never matches (-> "other").
C.AP_REASON = {
    KILL          = CURRENCY_CHANGE_REASON_KILL,
    KILL_TRANSFER = CURRENCY_CHANGE_REASON_PVP_KILL_TRANSFER,
    KEEP_OFFENSE  = CURRENCY_CHANGE_REASON_OFFENSIVE_KEEP_REWARD,
    KEEP_DEFENSE  = CURRENCY_CHANGE_REASON_DEFENSIVE_KEEP_REWARD,
    RESURRECT     = CURRENCY_CHANGE_REASON_PVP_RESURRECT,
    BATTLEGROUND  = CURRENCY_CHANGE_REASON_BATTLEGROUND,
}

-- ── Zone / AvA presence (Cyrodiil + Imperial City world) ──────────────────
C.EVENT_ZONE_CHANGED = EVENT_ZONE_CHANGED

-- ProgressReason buckets we care about for attribution (XP source).
C.PROGRESS_REASON_BATTLEGROUND = PROGRESS_REASON_BATTLEGROUND
C.PROGRESS_REASON_AVA          = PROGRESS_REASON_AVA
C.PROGRESS_REASON_KILL         = PROGRESS_REASON_KILL
C.PROGRESS_REASON_MEDAL        = PROGRESS_REASON_MEDAL

-- ── Competitive leaderboard / ranking ─────────────────────────────────────
C.EVENT_BATTLEGROUND_LEADERBOARD_DATA_RECEIVED = EVENT_BATTLEGROUND_LEADERBOARD_DATA_RECEIVED
C.BATTLEGROUND_LEADERBOARD_TYPE_COMPETITIVE    = BATTLEGROUND_LEADERBOARD_TYPE_COMPETITIVE
C.LEADERBOARD_DATA_READY                       = LEADERBOARD_DATA_READY
-- MMR activity keys (try champion first, then fall back).
C.LFG_ACTIVITY_BG_CHAMPION     = LFG_ACTIVITY_BATTLE_GROUND_CHAMPION
C.LFG_ACTIVITY_BG_NON_CHAMPION = LFG_ACTIVITY_BATTLE_GROUND_NON_CHAMPION
C.LFG_ACTIVITY_BG_LOW_LEVEL    = LFG_ACTIVITY_BATTLE_GROUND_LOW_LEVEL

-- ── Veterancy / Season reward-track (the "new" system) ────────────────────
C.EVENT_REWARD_TRACK_PROGRESS_GAINED   = EVENT_REWARD_TRACK_PROGRESS_GAINED
C.EVENT_ACTIVE_VETERANCY_SEASON_UPDATED = EVENT_ACTIVE_VETERANCY_SEASON_UPDATED
C.REWARD_TRACK_TYPE_AVA_VETERANCY      = REWARD_TRACK_TYPE_AVA_VETERANCY

-- ── Battleground team enum (3-team arena BGs, not AvA alliances) ───────────
C.BATTLEGROUND_TEAM_INVALID     = BATTLEGROUND_TEAM_INVALID
C.BATTLEGROUND_TEAM_FIRE_DRAKES = BATTLEGROUND_TEAM_FIRE_DRAKES
C.BATTLEGROUND_TEAM_PIT_DAEMONS = BATTLEGROUND_TEAM_PIT_DAEMONS
C.BATTLEGROUND_TEAM_STORM_LORDS = BATTLEGROUND_TEAM_STORM_LORDS

-- ── Match result enum -> string map (filled lazily; engine value -> label) ─
C.RESULT_LABEL = {
    [BATTLEGROUND_RESULT_WIN or -1]     = "WIN",
    [BATTLEGROUND_RESULT_LOSS or -2]    = "LOSS",
    [BATTLEGROUND_RESULT_TIE or -3]     = "TIE",
    [BATTLEGROUND_RESULT_INVALID or -4] = nil,
}

BGMeter.zenimax.constants = C
