-- bgmeter :: zenimax/constants.lua
-- The ZeniMax API boundary. Every raw engine enum bgmeter relies on is
-- re-exported here, namespaced, so the rest of the addon never reads a bare
-- global. If ZOS renames an enum, this is the single file that changes.

BGMeter = BGMeter or {}
local BGMeter = BGMeter

BGMeter.zenimax = BGMeter.zenimax or {}

local C = {}

-- ── Battleground match lifecycle ──────────────────────────────────────────
C.EVENT_ADD_ON_LOADED              = EVENT_ADD_ON_LOADED
C.EVENT_PLAYER_ACTIVATED          = EVENT_PLAYER_ACTIVATED
C.EVENT_PLAYER_COMBAT_STATE       = EVENT_PLAYER_COMBAT_STATE
C.EVENT_BATTLEGROUND_STATE_CHANGED = EVENT_BATTLEGROUND_STATE_CHANGED
C.EVENT_BATTLEGROUND_SCOREBOARD_UPDATED = EVENT_BATTLEGROUND_SCOREBOARD_UPDATED
C.EVENT_BATTLEGROUND_KILL          = EVENT_BATTLEGROUND_KILL

C.BATTLEGROUND_STATE_NONE      = BATTLEGROUND_STATE_NONE
C.BATTLEGROUND_STATE_PREROUND  = BATTLEGROUND_STATE_PREROUND
C.BATTLEGROUND_STATE_STARTING  = BATTLEGROUND_STATE_STARTING
C.BATTLEGROUND_STATE_RUNNING   = BATTLEGROUND_STATE_RUNNING
C.BATTLEGROUND_STATE_POSTROUND = BATTLEGROUND_STATE_POSTROUND
C.BATTLEGROUND_STATE_FINISHED  = BATTLEGROUND_STATE_FINISHED

-- ── Scoreboard per-player score types ─────────────────────────────────────
C.SCORE_TRACKER_TYPE_SCORE        = SCORE_TRACKER_TYPE_SCORE
C.SCORE_TRACKER_TYPE_KILL         = SCORE_TRACKER_TYPE_KILL
C.SCORE_TRACKER_TYPE_DEATH        = SCORE_TRACKER_TYPE_DEATH
C.SCORE_TRACKER_TYPE_ASSISTS      = SCORE_TRACKER_TYPE_ASSISTS
C.SCORE_TRACKER_TYPE_DAMAGE_DONE  = SCORE_TRACKER_TYPE_DAMAGE_DONE
C.SCORE_TRACKER_TYPE_HEALING_DONE = SCORE_TRACKER_TYPE_HEALING_DONE
C.SCORE_TRACKER_TYPE_DAMAGE_TAKEN = SCORE_TRACKER_TYPE_DAMAGE_TAKEN
C.SCORE_TRACKER_TYPE_FLAG_CAPTURED          = SCORE_TRACKER_TYPE_FLAG_CAPTURED
C.SCORE_TRACKER_TYPE_CAPTURE_DEFENSE_POINTS = SCORE_TRACKER_TYPE_CAPTURE_DEFENSE_POINTS
C.SCORE_TRACKER_TYPE_FLAG_CARRIED_TIME      = SCORE_TRACKER_TYPE_FLAG_CARRIED_TIME
C.SCORE_TRACKER_TYPE_KILLED_FLAG_CARRIER    = SCORE_TRACKER_TYPE_KILLED_FLAG_CARRIER

-- ── Progression: AP / XP / Champion ───────────────────────────────────────
C.EVENT_ALLIANCE_POINT_UPDATE = EVENT_ALLIANCE_POINT_UPDATE
C.EVENT_EXPERIENCE_GAIN       = EVENT_EXPERIENCE_GAIN
C.EVENT_CHAMPION_POINT_GAINED = EVENT_CHAMPION_POINT_GAINED

C.CURT_ALLIANCE_POINTS        = CURT_ALLIANCE_POINTS
C.CURRENCY_LOCATION_CHARACTER = CURRENCY_LOCATION_CHARACTER

-- ── AP source attribution (CurrencyChangeReason) ──────────────────────────
-- EVENT_ALLIANCE_POINT_UPDATE now passes a `reason` (CurrencyChangeReason) as
-- its 4th arg, so AP gains in Cyrodiil/IC can be split by what earned them.
-- These enums are nil-safe: an absent one simply never matches (-> "other").
C.AP_REASON = {
    KILL          = CURRENCY_CHANGE_REASON_KILL,
    KILL_TRANSFER = CURRENCY_CHANGE_REASON_PVP_KILL_TRANSFER,
    KEEP_OFFENSE  = CURRENCY_CHANGE_REASON_OFFENSIVE_KEEP_REWARD,
    KEEP_DEFENSE  = CURRENCY_CHANGE_REASON_DEFENSIVE_KEEP_REWARD,
    RESURRECT     = CURRENCY_CHANGE_REASON_PVP_RESURRECT,
    BATTLEGROUND  = CURRENCY_CHANGE_REASON_BATTLEGROUND,
}

-- ── Zone / AvA presence (Cyrodiil + Imperial City world) ──────────────────
C.EVENT_ZONE_CHANGED = EVENT_ZONE_CHANGED

-- ProgressReason buckets we care about for attribution (XP source).
C.PROGRESS_REASON_BATTLEGROUND = PROGRESS_REASON_BATTLEGROUND
C.PROGRESS_REASON_AVA          = PROGRESS_REASON_AVA
C.PROGRESS_REASON_KILL         = PROGRESS_REASON_KILL
C.PROGRESS_REASON_MEDAL        = PROGRESS_REASON_MEDAL

-- ── Competitive leaderboard / ranking ─────────────────────────────────────
C.EVENT_BATTLEGROUND_LEADERBOARD_DATA_RECEIVED = EVENT_BATTLEGROUND_LEADERBOARD_DATA_RECEIVED
C.BATTLEGROUND_LEADERBOARD_TYPE_COMPETITIVE    = BATTLEGROUND_LEADERBOARD_TYPE_COMPETITIVE
C.LEADERBOARD_DATA_READY                       = LEADERBOARD_DATA_READY
-- MMR activity keys (try champion first, then fall back).
C.LFG_ACTIVITY_BG_CHAMPION     = LFG_ACTIVITY_BATTLE_GROUND_CHAMPION
C.LFG_ACTIVITY_BG_NON_CHAMPION = LFG_ACTIVITY_BATTLE_GROUND_NON_CHAMPION
C.LFG_ACTIVITY_BG_LOW_LEVEL    = LFG_ACTIVITY_BATTLE_GROUND_LOW_LEVEL

-- ── Veterancy / Season reward-track (the "new" system) ────────────────────
C.EVENT_REWARD_TRACK_PROGRESS_GAINED   = EVENT_REWARD_TRACK_PROGRESS_GAINED
C.EVENT_ACTIVE_VETERANCY_SEASON_UPDATED = EVENT_ACTIVE_VETERANCY_SEASON_UPDATED
C.REWARD_TRACK_TYPE_AVA_VETERANCY      = REWARD_TRACK_TYPE_AVA_VETERANCY

-- ── Battleground team enum (3-team arena BGs, not AvA alliances) ───────────
C.BATTLEGROUND_TEAM_INVALID     = BATTLEGROUND_TEAM_INVALID
C.BATTLEGROUND_TEAM_FIRE_DRAKES = BATTLEGROUND_TEAM_FIRE_DRAKES
C.BATTLEGROUND_TEAM_PIT_DAEMONS = BATTLEGROUND_TEAM_PIT_DAEMONS
C.BATTLEGROUND_TEAM_STORM_LORDS = BATTLEGROUND_TEAM_STORM_LORDS

C.EVENT_CAPTURE_AREA_STATE_CHANGED = EVENT_CAPTURE_AREA_STATE_CHANGED
C.EVENT_CAPTURE_FLAG_STATE_CHANGED = EVENT_CAPTURE_FLAG_STATE_CHANGED
C.EVENT_MURDERBALL_STATE_CHANGED   = EVENT_MURDERBALL_STATE_CHANGED
C.OBJECTIVE_CAPTURE_AREA           = OBJECTIVE_CAPTURE_AREA

C.BATTLEGROUND_GAME_TYPE_DOMINATION       = BATTLEGROUND_GAME_TYPE_DOMINATION
C.BATTLEGROUND_GAME_TYPE_CRAZY_KING       = BATTLEGROUND_GAME_TYPE_CRAZY_KING
C.BATTLEGROUND_GAME_TYPE_KING_OF_THE_HILL = BATTLEGROUND_GAME_TYPE_KING_OF_THE_HILL

local function put(map, key, label)
    if key ~= nil then map[key] = label end
end

C.OBJ_EVENT_INFLUENCE = OBJECTIVE_CONTROL_EVENT_AREA_INFLUENCE_CHANGED

C.BG_STATE_LABEL = {}
local function put_state(key, label)
    if key ~= nil then C.BG_STATE_LABEL[key] = label end
end
put_state(BATTLEGROUND_STATE_NONE,      "none")
put_state(BATTLEGROUND_STATE_PREROUND,  "preround")
put_state(BATTLEGROUND_STATE_STARTING,  "starting")
put_state(BATTLEGROUND_STATE_RUNNING,   "running")
put_state(BATTLEGROUND_STATE_POSTROUND, "postround")
put_state(BATTLEGROUND_STATE_FINISHED,  "finished")

C.GAME_TYPE_LABEL = {}
local function put_gt(key, label)
    if key ~= nil then C.GAME_TYPE_LABEL[key] = label end
end
put_gt(BATTLEGROUND_GAME_TYPE_NONE,             "none")
put_gt(BATTLEGROUND_GAME_TYPE_DEATHMATCH,       "deathmatch")
put_gt(BATTLEGROUND_GAME_TYPE_DOMINATION,       "domination")
put_gt(BATTLEGROUND_GAME_TYPE_CRAZY_KING,       "crazy_king")
put_gt(BATTLEGROUND_GAME_TYPE_KING_OF_THE_HILL, "king_of_the_hill")
put_gt(BATTLEGROUND_GAME_TYPE_CAPTURE_THE_FLAG, "capture_the_flag")
put_gt(BATTLEGROUND_GAME_TYPE_MURDERBALL,       "murderball")

C.OBJ_EVENT_LABEL = {}
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_NONE,                   "none")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_CAPTURED,               "captured")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_RECAPTURED,             "recaptured")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_UNDER_ATTACK,           "under_attack")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_ASSAULTED,              "assaulted")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_LOST,                   "lost")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_FULLY_HELD,             "fully_held")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_AREA_NEUTRAL,           "neutral")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_AREA_INFLUENCE_CHANGED, "influence")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_DEACTIVATED,            "deactivated")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_DEACTIVATE_PENDING,     "deactivate_pending")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_HIDDEN,                 "hidden")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_FLAG_TAKEN,             "flag_taken")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_FLAG_DROPPED,           "flag_dropped")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED,          "flag_returned")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED_BY_TIMER, "flag_timer_return")
put(C.OBJ_EVENT_LABEL, OBJECTIVE_CONTROL_EVENT_FLAG_SPAWNED,           "flag_spawned")

C.OBJ_STATE_LABEL = {}
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_UNKNOWN,                      "unknown")
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_AREA_INACTIVE,                "inactive")
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_AREA_NO_CONTROL,              "no_control")
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_AREA_BELOW_CONTROL_THRESHOLD, "below_threshold")
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_AREA_ABOVE_CONTROL_THRESHOLD, "above_threshold")
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_AREA_MAX_CONTROL,             "max_control")
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_POINT_CONTROLLED,             "controlled")
put(C.OBJ_STATE_LABEL, OBJECTIVE_CONTROL_STATE_POINT_TRANSITIONING,          "transitioning")

C.OBJ_LETTER = {}
put(C.OBJ_LETTER, OBJECTIVE_DESIGNATION_A, "A")
put(C.OBJ_LETTER, OBJECTIVE_DESIGNATION_B, "B")
put(C.OBJ_LETTER, OBJECTIVE_DESIGNATION_C, "C")
put(C.OBJ_LETTER, OBJECTIVE_DESIGNATION_D, "D")

-- ── Match result enum -> string map (filled lazily; engine value -> label) ─
C.RESULT_LABEL = {
    [BATTLEGROUND_RESULT_WIN or -1]     = "WIN",
    [BATTLEGROUND_RESULT_LOSS or -2]    = "LOSS",
    [BATTLEGROUND_RESULT_TIE or -3]     = "TIE",
    [BATTLEGROUND_RESULT_INVALID or -4] = nil,
}

BGMeter.zenimax.constants = C
